FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of the app
COPY . .

# Expose Streamlit port
EXPOSE 8501

# Run Streamlit app
# CMD ["streamlit", "run", "churnx-ai.py", "--server.port=8501", "--server.address=0.0.0.0"]
CMD ["streamlit", "run", "churnx-ai.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.enableXsrfProtection=false", "--server.enableCORS=false", "--server.headless=true"]